APP_NAME = core-ui
APP_PATH = core-ui
BUILDPACK = eu.gcr.io/kyma-project/test-infra/buildpack-node:v20191009-19b4b28
SCRIPTS_DIR = $(realpath $(shell pwd)/..)/scripts

include $(SCRIPTS_DIR)/makefile-node-common.mk
